// Code generated by MockGen. DO NOT EDIT.
// Source: utils/metadata.go
//
// Generated by this command:
//
//	mockgen -source=utils/metadata.go -destination=./mocks/metadata_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks
