// Code generated by MockGen. DO NOT EDIT.
// Source: ./errors/publish_errors.go
//
// Generated by this command:
//
//	mockgen -source=./errors/publish_errors.go -destination=./mocks/publish_errors_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks
