// Code generated by MockGen. DO NOT EDIT.
// Source: ./types/round/types.go
//
// Generated by this command:
//
//	mockgen -source=./types/round/types.go -destination=./mocks/round_types_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks
