package roundevents

import sharedevents "github.com/Black-And-White-Club/frolf-bot-shared/events/shared"

// GetV1Registry returns all modern events for the round functional area
func GetV1Registry() map[string]sharedevents.EventInfo {
	return map[string]sharedevents.EventInfo{
		// Creation flow
		RoundCreationRequestedV1:     {Payload: &CreateRoundRequestedPayloadV1{}, Summary: "Round Creation Requested", Description: "User initiated round creation request.", Producer: sharedevents.Actor{Service: sharedevents.ServiceDiscord, Module: "round"}, Consumers: []sharedevents.Actor{{Service: sharedevents.ServiceBackend, Module: "round"}}},
		RoundValidationPassedV1:      {Payload: &RoundValidationPassedPayloadV1{}, Summary: "Round Validation Passed", Description: "Round creation input passed validation.", Producer: sharedevents.Actor{Service: sharedevents.ServiceBackend, Module: "round"}, Consumers: []sharedevents.Actor{{Service: sharedevents.ServiceBackend, Module: "round"}}},
		RoundValidationFailedV1:      {Payload: &RoundValidationFailedPayloadV1{}, Summary: "Round Validation Failed", Description: "Round creation input failed validation.", Producer: sharedevents.Actor{Service: sharedevents.ServiceBackend, Module: "round"}, Consumers: []sharedevents.Actor{{Service: sharedevents.ServiceDiscord, Module: "round"}}},
		RoundDateTimeParsedV1:        {Payload: &RoundDateTimeParsedPayloadV1{}, Summary: "Round Datetime Parsed", Description: "Natural language datetime parsed for round creation.", Producer: sharedevents.Actor{Service: sharedevents.ServiceBackend, Module: "round"}, Consumers: []sharedevents.Actor{{Service: sharedevents.ServiceBackend, Module: "round"}}},
		RoundEntityCreatedV1:         {Payload: &RoundEntityCreatedPayloadV1{}, Summary: "Round Entity Created", Description: "In-memory round entity was created.", Producer: sharedevents.Actor{Service: sharedevents.ServiceBackend, Module: "round"}, Consumers: []sharedevents.Actor{}},
		RoundStoredV1:                {Payload: &RoundStoredPayloadV1{}, Summary: "Round Stored", Description: "Round entity persisted to storage.", Producer: sharedevents.Actor{Service: sharedevents.ServiceBackend, Module: "round"}, Consumers: []sharedevents.Actor{{Service: sharedevents.ServiceBackend, Module: "round"}}},
		RoundScheduledV1:             {Payload: &RoundScheduledPayloadV1{}, Summary: "Round Scheduled", Description: "Round reminders and start events scheduled.", Producer: sharedevents.Actor{Service: sharedevents.ServiceBackend, Module: "round"}, Consumers: []sharedevents.Actor{{Service: sharedevents.ServiceBackend, Module: "round"}, {Service: sharedevents.ServiceDiscord, Module: "round"}}},
		RoundScheduleFailedV1:        {Payload: &RoundScheduleFailedPayloadV1{}, Summary: "Round Schedule Failed", Description: "Scheduling of reminders/events failed.", Producer: sharedevents.Actor{Service: sharedevents.ServiceBackend, Module: "round"}, Consumers: []sharedevents.Actor{}},
		RoundCreatedV1:               {Payload: &RoundCreatedPayloadV1{}, Summary: "Round Created", Description: "Round creation completed successfully.", Producer: sharedevents.Actor{Service: sharedevents.ServiceBackend, Module: "round"}, Consumers: []sharedevents.Actor{{Service: sharedevents.ServiceDiscord, Module: "round"}}},
		RoundCreationFailedV1:        {Payload: &RoundCreationFailedPayloadV1{}, Summary: "Round Creation Failed", Description: "Round creation failed at some step.", Producer: sharedevents.Actor{Service: sharedevents.ServiceBackend, Module: "round"}, Consumers: []sharedevents.Actor{{Service: sharedevents.ServiceDiscord, Module: "round"}}},
		RoundEventMessageIDUpdatedV1: {Payload: &RoundEventCreatedPayloadV1{}, Summary: "Round Event Message ID Updated", Description: "Discord message ID was updated for a round.", Producer: sharedevents.Actor{Service: sharedevents.ServiceBackend, Module: "round"}, Consumers: []sharedevents.Actor{{Service: sharedevents.ServiceDiscord, Module: "round"}}},
		RoundEventMessageIDUpdateV1:  {Payload: &RoundMessageIDUpdatePayloadV1{}, Summary: "Round Event Message ID Update", Description: "Request to update a round's message ID.", Producer: sharedevents.Actor{Service: sharedevents.ServiceDiscord, Module: "round"}, Consumers: []sharedevents.Actor{{Service: sharedevents.ServiceBackend, Module: "round"}}},
		RoundErrorV1:                 {Payload: &RoundErrorPayloadV1{}, Summary: "Round Error", Description: "General round operation error.", Producer: sharedevents.Actor{Service: sharedevents.ServiceBackend, Module: "round"}, Consumers: []sharedevents.Actor{{Service: sharedevents.ServiceDiscord, Module: "round"}}},
		RoundTraceEventV1:            {Payload: &sharedevents.TracePayloadV1{}, Summary: "Round Trace Event", Description: "Observability trace event for round operations.", Producer: sharedevents.Actor{Service: sharedevents.ServiceBackend, Module: "round"}, Consumers: []sharedevents.Actor{}},

		// Participant flow
		RoundParticipantJoinRequestedV1:           {Payload: &ParticipantJoinRequestPayloadV1{}, Summary: "Participant Join Requested", Description: "User requests to join a round.", Producer: sharedevents.Actor{Service: sharedevents.ServiceDiscord, Module: "round"}, Consumers: []sharedevents.Actor{{Service: sharedevents.ServiceBackend, Module: "round"}}},
		RoundParticipantJoinValidationRequestedV1: {Payload: &ParticipantJoinValidationRequestPayloadV1{}, Summary: "Participant Join Validation Requested", Description: "Request issued to validate a join.", Producer: sharedevents.Actor{Service: sharedevents.ServiceBackend, Module: "round"}, Consumers: []sharedevents.Actor{}},
		RoundParticipantJoinValidatedV1:           {Payload: &ParticipantJoinValidatedPayloadV1{}, Summary: "Participant Join Validated", Description: "Join request validated successfully.", Producer: sharedevents.Actor{Service: sharedevents.ServiceBackend, Module: "round"}, Consumers: []sharedevents.Actor{{Service: sharedevents.ServiceBackend, Module: "round"}}},
		RoundParticipantJoinedV1:                  {Payload: &ParticipantJoinedPayloadV1{}, Summary: "Participant Joined", Description: "Participant successfully added to round.", Producer: sharedevents.Actor{Service: sharedevents.ServiceBackend, Module: "round"}, Consumers: []sharedevents.Actor{{Service: sharedevents.ServiceDiscord, Module: "round"}}},
		RoundParticipantJoinErrorV1:               {Payload: &RoundParticipantJoinErrorPayloadV1{}, Summary: "Participant Join Error", Description: "Join request failed.", Producer: sharedevents.Actor{Service: sharedevents.ServiceBackend, Module: "round"}, Consumers: []sharedevents.Actor{}},
		RoundParticipantDeclinedV1:                {Payload: &ParticipantDeclinedPayloadV1{}, Summary: "Participant Declined", Description: "User declined to join.", Producer: sharedevents.Actor{Service: sharedevents.ServiceBackend, Module: "round"}, Consumers: []sharedevents.Actor{}},
		RoundParticipantRemovalRequestedV1:        {Payload: &ParticipantRemovalRequestPayloadV1{}, Summary: "Participant Removal Requested", Description: "Request to remove a participant.", Producer: sharedevents.Actor{Service: sharedevents.ServiceDiscord, Module: "round"}, Consumers: []sharedevents.Actor{{Service: sharedevents.ServiceBackend, Module: "round"}}},
		RoundParticipantRemovedV1:                 {Payload: &ParticipantRemovedPayloadV1{}, Summary: "Participant Removed", Description: "Participant removed from the round.", Producer: sharedevents.Actor{Service: sharedevents.ServiceBackend, Module: "round"}, Consumers: []sharedevents.Actor{{Service: sharedevents.ServiceDiscord, Module: "round"}}},
		RoundParticipantRemovalErrorV1:            {Payload: &ParticipantRemovalErrorPayloadV1{}, Summary: "Participant Removal Error", Description: "Participant removal failed.", Producer: sharedevents.Actor{Service: sharedevents.ServiceBackend, Module: "round"}, Consumers: []sharedevents.Actor{}},
		RoundParticipantStatusErrorV1:             {Payload: &ParticipantUpdateErrorPayloadV1{}, Summary: "Participant Status Error", Description: "General participant status error.", Producer: sharedevents.Actor{Service: sharedevents.ServiceBackend, Module: "round"}, Consumers: []sharedevents.Actor{}},
		RoundParticipantStatusFoundV1:             {Payload: &ParticipantStatusFoundPayloadV1{}, Summary: "Participant Status Found", Description: "Participant status found for a round.", Producer: sharedevents.Actor{Service: sharedevents.ServiceBackend, Module: "round"}, Consumers: []sharedevents.Actor{{Service: sharedevents.ServiceBackend, Module: "round"}}},
		RoundParticipantStatusCheckErrorV1:        {Payload: &ParticipantStatusCheckErrorPayloadV1{}, Summary: "Participant Status Check Error", Description: "Error checking participant status.", Producer: sharedevents.Actor{Service: sharedevents.ServiceBackend, Module: "round"}, Consumers: []sharedevents.Actor{}},
		RoundParticipantUpdateErrorV1:             {Payload: &ParticipantUpdateErrorPayloadV1{}, Summary: "Participant Update Error", Description: "Participant update failed.", Producer: sharedevents.Actor{Service: sharedevents.ServiceBackend, Module: "round"}, Consumers: []sharedevents.Actor{{Service: sharedevents.ServiceDiscord, Module: "round"}}},
		RoundParticipantStatusUpdateRequestedV1:   {Payload: &ParticipantStatusRequestPayloadV1{}, Summary: "Participant Status Update Requested", Description: "Request to update participant status.", Producer: sharedevents.Actor{Service: sharedevents.ServiceDiscord, Module: "round"}, Consumers: []sharedevents.Actor{{Service: sharedevents.ServiceBackend, Module: "round"}}},
		RoundParticipantsUpdatedV1:                {Payload: &RoundParticipantsUpdatedPayloadV1{}, Summary: "Round Participants Updated", Description: "Participants updated due to tag changes.", Producer: sharedevents.Actor{Service: sharedevents.ServiceBackend, Module: "round"}, Consumers: []sharedevents.Actor{}},

		// Lifecycle
		RoundStartedV1:            {Payload: &RoundStartedPayloadV1{}, Summary: "Round Started", Description: "Scheduled round start reached.", Producer: sharedevents.Actor{Service: sharedevents.ServiceBackend, Module: "round"}, Consumers: []sharedevents.Actor{}},
		RoundStartedDiscordV1:     {Payload: &DiscordRoundStartPayloadV1{}, Summary: "Round Started (Discord)", Description: "Discord-specific start notification.", Producer: sharedevents.Actor{Service: sharedevents.ServiceBackend, Module: "round"}, Consumers: []sharedevents.Actor{{Service: sharedevents.ServiceDiscord, Module: "round"}}},
		RoundStartFailedV1:        {Payload: &RoundStartFailedPayloadV1{}, Summary: "Round Start Failed", Description: "Processing round start failed.", Producer: sharedevents.Actor{Service: sharedevents.ServiceBackend, Module: "round"}, Consumers: []sharedevents.Actor{}},
		RoundStartRequestedV1:     {Payload: &RoundStartRequestedPayloadV1{}, Summary: "Round Start Requested", Description: "Worker requested to start round.", Producer: sharedevents.Actor{Service: sharedevents.ServiceBackend, Module: "round"}, Consumers: []sharedevents.Actor{}},
		RoundFinalizedV1:          {Payload: &RoundFinalizedPayloadV1{}, Summary: "Round Finalized", Description: "Round finalized and DB updated.", Producer: sharedevents.Actor{Service: sharedevents.ServiceBackend, Module: "round"}, Consumers: []sharedevents.Actor{}}, // TODO: external consumers (Unknown/External)
		RoundFinalizedDiscordV1:   {Payload: &RoundFinalizedDiscordPayloadV1{}, Summary: "Round Finalized (Discord)", Description: "Discord-specific finalization payload.", Producer: sharedevents.Actor{Service: sharedevents.ServiceBackend, Module: "round"}, Consumers: []sharedevents.Actor{{Service: sharedevents.ServiceDiscord, Module: "round"}}},
		RoundCompletedV1:          {Payload: &RoundCompletedPayloadV1{}, Summary: "Round Completed", Description: "Round processing completed.", Producer: sharedevents.Actor{Service: sharedevents.ServiceBackend, Module: "round"}, Consumers: []sharedevents.Actor{}},
		RoundFinalizationErrorV1:  {Payload: &RoundFinalizationErrorPayloadV1{}, Summary: "Round Finalization Error", Description: "Finalization error occurred.", Producer: sharedevents.Actor{Service: sharedevents.ServiceBackend, Module: "round"}, Consumers: []sharedevents.Actor{}},
		RoundFinalizationFailedV1: {Payload: &RoundFinalizationFailedPayloadV1{}, Summary: "Round Finalization Failed", Description: "Finalization operation-specific failure.", Producer: sharedevents.Actor{Service: sharedevents.ServiceBackend, Module: "round"}, Consumers: []sharedevents.Actor{}},
		RoundReminderScheduledV1:  {Payload: &DiscordReminderPayloadV1{}, Summary: "Round Reminder Scheduled", Description: "Reminder scheduled for a round.", Producer: sharedevents.Actor{Service: sharedevents.ServiceBackend, Module: "round"}, Consumers: []sharedevents.Actor{}},
		RoundReminderSentV1:       {Payload: &DiscordReminderPayloadV1{}, Summary: "Round Reminder Sent", Description: "Reminder sent to Discord.", Producer: sharedevents.Actor{Service: sharedevents.ServiceBackend, Module: "round"}, Consumers: []sharedevents.Actor{{Service: sharedevents.ServiceDiscord, Module: "round"}}},
		RoundReminderFailedV1:     {Payload: &RoundReminderFailedPayloadV1{}, Summary: "Round Reminder Failed", Description: "Reminder processing failed.", Producer: sharedevents.Actor{Service: sharedevents.ServiceBackend, Module: "round"}, Consumers: []sharedevents.Actor{}},

		// Update flow
		RoundUpdateRequestedV1: {Payload: &UpdateRoundRequestedPayloadV1{}, Summary: "Round Update Requested", Description: "User requested round update.", Producer: sharedevents.Actor{Service: sharedevents.ServiceDiscord, Module: "round"}, Consumers: []sharedevents.Actor{{Service: sharedevents.ServiceBackend, Module: "round"}}},
		RoundUpdateValidatedV1: {Payload: &RoundUpdateValidatedPayloadV1{}, Summary: "Round Update Validated", Description: "Update request validated.", Producer: sharedevents.Actor{Service: sharedevents.ServiceBackend, Module: "round"}, Consumers: []sharedevents.Actor{}},
		RoundFetchedV1:         {Payload: &RoundFetchedPayloadV1{}, Summary: "Round Fetched", Description: "Round fetched for update.", Producer: sharedevents.Actor{Service: sharedevents.ServiceBackend, Module: "round"}, Consumers: []sharedevents.Actor{{Service: sharedevents.ServiceBackend, Module: "round"}}},
		RoundEntityUpdatedV1:   {Payload: &RoundEntityUpdatedPayloadV1{}, Summary: "Round Entity Updated", Description: "Round entity updated in memory.", Producer: sharedevents.Actor{Service: sharedevents.ServiceBackend, Module: "round"}, Consumers: []sharedevents.Actor{{Service: sharedevents.ServiceBackend, Module: "round"}}},
		RoundUpdatedV1:         {Payload: &RoundUpdateSuccessPayloadV1{}, Summary: "Round Updated", Description: "Round update completed.", Producer: sharedevents.Actor{Service: sharedevents.ServiceBackend, Module: "round"}, Consumers: []sharedevents.Actor{{Service: sharedevents.ServiceDiscord, Module: "round"}}},
		RoundUpdateSuccessV1:   {Payload: &RoundUpdateSuccessPayloadV1{}, Summary: "Round Update Success", Description: "Round update completed successfully.", Producer: sharedevents.Actor{Service: sharedevents.ServiceBackend, Module: "round"}, Consumers: []sharedevents.Actor{{Service: sharedevents.ServiceDiscord, Module: "round"}}},
		RoundUpdateErrorV1:     {Payload: &RoundUpdateErrorPayloadV1{}, Summary: "Round Update Error", Description: "Round update failed.", Producer: sharedevents.Actor{Service: sharedevents.ServiceBackend, Module: "round"}, Consumers: []sharedevents.Actor{{Service: sharedevents.ServiceDiscord, Module: "round"}}},
		RoundScheduleUpdatedV1: {Payload: &RoundScheduleUpdatePayloadV1{}, Summary: "Round Schedule Updated", Description: "Round schedule was updated.", Producer: sharedevents.Actor{Service: sharedevents.ServiceBackend, Module: "round"}, Consumers: []sharedevents.Actor{}},
		RoundUpdateRescheduleV1: {Payload: &RoundUpdateReschedulePayloadV1{}, Summary: "Round Update Reschedule", Description: "Round update requires rescheduling.", Producer: sharedevents.Actor{Service: sharedevents.ServiceBackend, Module: "round"}, Consumers: []sharedevents.Actor{{Service: sharedevents.ServiceBackend, Module: "round"}}},
		RoundStateUpdatedV1:      {Payload: &RoundStateUpdatedPayloadV1{}, Summary: "Round State Updated", Description: "Round state updated.", Producer: sharedevents.Actor{Service: sharedevents.ServiceBackend, Module: "round"}, Consumers: []sharedevents.Actor{{Service: sharedevents.ServiceDiscord, Module: "round"}}},
		RoundsUpdatedV1:          {Payload: &RoundsUpdatedPayloadV1{}, Summary: "Rounds Updated", Description: "Multiple rounds updated in bulk.", Producer: sharedevents.Actor{Service: sharedevents.ServiceBackend, Module: "round"}, Consumers: []sharedevents.Actor{{Service: sharedevents.ServiceDiscord, Module: "round"}}},

		// Score update flow
		RoundScoreUpdateRequestedV1:    {Payload: &ScoreUpdateRequestPayloadV1{}, Summary: "Round Score Update Requested", Description: "User submitted a score update.", Producer: sharedevents.Actor{Service: sharedevents.ServiceDiscord, Module: "round"}, Consumers: []sharedevents.Actor{{Service: sharedevents.ServiceBackend, Module: "round"}}},
		RoundScoreBulkUpdateRequestedV1: {Payload: &ScoreBulkUpdateRequestPayloadV1{}, Summary: "Round Score Bulk Update Requested", Description: "Bulk score override requested.", Producer: sharedevents.Actor{Service: sharedevents.ServiceBackend, Module: "score"}, Consumers: []sharedevents.Actor{{Service: sharedevents.ServiceBackend, Module: "round"}}},
		RoundScoreUpdateValidatedV1:    {Payload: &ScoreUpdateValidatedPayloadV1{}, Summary: "Round Score Update Validated", Description: "Score update validated.", Producer: sharedevents.Actor{Service: sharedevents.ServiceBackend, Module: "round"}, Consumers: []sharedevents.Actor{{Service: sharedevents.ServiceBackend, Module: "round"}}},
		RoundParticipantScoreUpdatedV1: {Payload: &ParticipantScoreUpdatedPayloadV1{}, Summary: "Round Participant Score Updated", Description: "Participant score updated.", Producer: sharedevents.Actor{Service: sharedevents.ServiceBackend, Module: "round"}, Consumers: []sharedevents.Actor{{Service: sharedevents.ServiceBackend, Module: "round"}, {Service: sharedevents.ServiceDiscord, Module: "round"}}},
		RoundScoresBulkUpdatedV1:       {Payload: &RoundScoresBulkUpdatedPayloadV1{}, Summary: "Round Scores Bulk Updated", Description: "Bulk score overrides applied to a round.", Producer: sharedevents.Actor{Service: sharedevents.ServiceBackend, Module: "round"}, Consumers: []sharedevents.Actor{{Service: sharedevents.ServiceDiscord, Module: "round"}}},
		RoundScoreUpdateErrorV1:        {Payload: &RoundScoreUpdateErrorPayloadV1{}, Summary: "Round Score Update Error", Description: "Score update failed.", Producer: sharedevents.Actor{Service: sharedevents.ServiceBackend, Module: "round"}, Consumers: []sharedevents.Actor{{Service: sharedevents.ServiceDiscord, Module: "round"}}},
		RoundAllScoresSubmittedV1:      {Payload: &AllScoresSubmittedPayloadV1{}, Summary: "Round All Scores Submitted", Description: "All scores submitted for a round.", Producer: sharedevents.Actor{Service: sharedevents.ServiceBackend, Module: "round"}, Consumers: []sharedevents.Actor{{Service: sharedevents.ServiceBackend, Module: "round"}}},
		RoundScoresPartiallySubmittedV1: {Payload: &ScoresPartiallySubmittedPayloadV1{}, Summary: "Round Scores Partially Submitted", Description: "Some participant scores still pending.", Producer: sharedevents.Actor{Service: sharedevents.ServiceBackend, Module: "round"}, Consumers: []sharedevents.Actor{{Service: sharedevents.ServiceDiscord, Module: "round"}}},
		RoundScoresNotificationV1:       {Payload: &RoundScoresNotificationPayloadV1{}, Summary: "Round Scores Notification", Description: "Notification about round scores.", Producer: sharedevents.Actor{Service: sharedevents.ServiceBackend, Module: "round"}, Consumers: []sharedevents.Actor{{Service: sharedevents.ServiceDiscord, Module: "round"}}},

		// Import/scorecard
		ScorecardUploadedV1:         {Payload: &ScorecardUploadedPayloadV1{}, Summary: "Scorecard Uploaded", Description: "User uploaded a scorecard file.", Producer: sharedevents.Actor{Service: sharedevents.ServiceDiscord, Module: "round"}, Consumers: []sharedevents.Actor{{Service: sharedevents.ServiceBackend, Module: "round"}}},
		ScorecardURLRequestedV1:     {Payload: &ScorecardURLRequestedPayloadV1{}, Summary: "Scorecard URL Requested", Description: "User provided a UDisc URL for import.", Producer: sharedevents.Actor{Service: sharedevents.ServiceDiscord, Module: "round"}, Consumers: []sharedevents.Actor{{Service: sharedevents.ServiceBackend, Module: "round"}}},
		ScorecardParseRequestedV1:   {Payload: &ScorecardUploadedPayloadV1{}, Summary: "Scorecard Parse Requested", Description: "Request to parse uploaded scorecard.", Producer: sharedevents.Actor{Service: sharedevents.ServiceBackend, Module: "round"}, Consumers: []sharedevents.Actor{}},
		ScorecardParsedV1:           {Payload: &ParsedScorecardPayloadV1{}, Summary: "Scorecard Parsed", Description: "Scorecard parsed successfully.", Producer: sharedevents.Actor{Service: sharedevents.ServiceBackend, Module: "round"}, Consumers: []sharedevents.Actor{}},
		ScorecardParsedForUserV1:    {Payload: &ParsedScorecardPayloadV1{}, Summary: "Scorecard Parsed (User)", Description: "Fan-out parsed payload for user module.", Producer: sharedevents.Actor{Service: sharedevents.ServiceBackend, Module: "round"}, Consumers: []sharedevents.Actor{}},
		ScorecardParseFailedV1:      {Payload: &ScorecardParseFailedPayloadV1{}, Summary: "Scorecard Parse Failed", Description: "Scorecard parsing failed.", Producer: sharedevents.Actor{Service: sharedevents.ServiceBackend, Module: "round"}, Consumers: []sharedevents.Actor{}},
		ImportCompletedV1:           {Payload: &ImportCompletedPayloadV1{}, Summary: "Import Completed", Description: "Import completed successfully.", Producer: sharedevents.Actor{Service: sharedevents.ServiceBackend, Module: "round"}, Consumers: []sharedevents.Actor{}},
		ImportConflictDetectedV1:    {Payload: &ImportConflictDetectedPayloadV1{}, Summary: "Import Conflict Detected", Description: "Import conflict detected for a round.", Producer: sharedevents.Actor{Service: sharedevents.ServiceBackend, Module: "round"}, Consumers: []sharedevents.Actor{{Service: sharedevents.ServiceDiscord, Module: "round"}}},
		ImportOverwriteConfirmedV1:  {Payload: &ImportOverwriteConfirmedPayloadV1{}, Summary: "Import Overwrite Confirmed", Description: "User confirmed score import overwrite.", Producer: sharedevents.Actor{Service: sharedevents.ServiceDiscord, Module: "round"}, Consumers: []sharedevents.Actor{{Service: sharedevents.ServiceBackend, Module: "round"}}},
		ImportFailedV1:              {Payload: &ImportFailedPayloadV1{}, Summary: "Import Failed", Description: "Import failed.", Producer: sharedevents.Actor{Service: sharedevents.ServiceBackend, Module: "round"}, Consumers: []sharedevents.Actor{{Service: sharedevents.ServiceDiscord, Module: "round"}}},
		RoundParticipantAutoAddedV1: {Payload: &RoundParticipantAutoAddedPayloadV1{}, Summary: "Round Participant Auto Added", Description: "Participant auto-added during import.", Producer: sharedevents.Actor{Service: sharedevents.ServiceBackend, Module: "round"}, Consumers: []sharedevents.Actor{}},
		RoundScoresImportedV1:       {Payload: &RoundScoresImportedPayloadV1{}, Summary: "Round Scores Imported", Description: "Scores imported into a round.", Producer: sharedevents.Actor{Service: sharedevents.ServiceBackend, Module: "round"}, Consumers: []sharedevents.Actor{{Service: sharedevents.ServiceBackend, Module: "score"}}},
		RoundScoresFinalizedV1:      {Payload: &RoundScoresFinalizedPayloadV1{}, Summary: "Round Scores Finalized", Description: "Imported scores finalized for a round.", Producer: sharedevents.Actor{Service: sharedevents.ServiceBackend, Module: "round"}, Consumers: []sharedevents.Actor{{Service: sharedevents.ServiceDiscord, Module: "round"}}},

		// Retrieval / authorization
		GetRoundRequestedV1:    {Payload: &GetRoundRequestPayloadV1{}, Summary: "Get Round Requested", Description: "Round data retrieval requested.", Producer: sharedevents.Actor{Service: sharedevents.ServiceDiscord, Module: "round"}, Consumers: []sharedevents.Actor{{Service: sharedevents.ServiceBackend, Module: "round"}}},
		RoundRetrievedV1:       {Payload: &RoundRetrievedPayloadV1{}, Summary: "Round Retrieved", Description: "Round data retrieved.", Producer: sharedevents.Actor{Service: sharedevents.ServiceBackend, Module: "round"}, Consumers: []sharedevents.Actor{{Service: sharedevents.ServiceDiscord, Module: "round"}}},
		RoundRetrievalFailedV1: {Payload: &RoundRetrievalFailedPayloadV1{}, Summary: "Round Retrieval Failed", Description: "Failed to retrieve round.", Producer: sharedevents.Actor{Service: sharedevents.ServiceBackend, Module: "round"}, Consumers: []sharedevents.Actor{}},
		RoundUserRoleCheckRequestedV1: {Payload: &UserRoleCheckRequestPayloadV1{}, Summary: "Round User Role Check Requested", Description: "Request to check user role for round access.", Producer: sharedevents.Actor{Service: sharedevents.ServiceBackend, Module: "round"}, Consumers: []sharedevents.Actor{{Service: sharedevents.ServiceBackend, Module: "round"}}},
		RoundUserRoleCheckResultV1:    {Payload: &UserRoleCheckResultPayloadV1{}, Summary: "Round User Role Check Result", Description: "User role check result for a round.", Producer: sharedevents.Actor{Service: sharedevents.ServiceBackend, Module: "round"}, Consumers: []sharedevents.Actor{{Service: sharedevents.ServiceBackend, Module: "round"}}},
		RoundUserRoleCheckErrorV1:     {Payload: &RoundUserRoleCheckErrorPayloadV1{}, Summary: "Round User Role Check Error", Description: "User role check failed.", Producer: sharedevents.Actor{Service: sharedevents.ServiceBackend, Module: "round"}, Consumers: []sharedevents.Actor{{Service: sharedevents.ServiceDiscord, Module: "round"}}},
		RoundEventsSubjectV1:          {Payload: &RoundEventEnvelopePayloadV1{}, Summary: "Round Event Envelope", Description: "Generic round event envelope for fan-out/aggregation.", Producer: sharedevents.Actor{Service: sharedevents.ServiceBackend, Module: "eventbus"}, Consumers: []sharedevents.Actor{{Service: sharedevents.ServiceBackend, Module: "round"}}},
		DelayedMessagesSubjectV1:      {Payload: &DelayedMessagePayloadV1{}, Summary: "Delayed Messages", Description: "Messages scheduled for delayed delivery.", Producer: sharedevents.Actor{Service: sharedevents.ServiceBackend, Module: "eventbus"}, Consumers: []sharedevents.Actor{{Service: sharedevents.ServiceBackend, Module: "round"}}},

		// Delete flow
		RoundDeleteRequestedV1:  {Payload: &RoundDeleteRequestPayloadV1{}, Summary: "Round Delete Requested", Description: "Request to delete a round.", Producer: sharedevents.Actor{Service: sharedevents.ServiceDiscord, Module: "round"}, Consumers: []sharedevents.Actor{{Service: sharedevents.ServiceBackend, Module: "round"}}},
		RoundDeleteValidatedV1:  {Payload: &RoundDeleteValidatedPayloadV1{}, Summary: "Round Delete Validated", Description: "Delete request validated.", Producer: sharedevents.Actor{Service: sharedevents.ServiceBackend, Module: "round"}, Consumers: []sharedevents.Actor{}},
		RoundToDeleteFetchedV1:  {Payload: &RoundToDeleteFetchedPayloadV1{}, Summary: "Round To Delete Fetched", Description: "Fetched round to be deleted.", Producer: sharedevents.Actor{Service: sharedevents.ServiceBackend, Module: "round"}, Consumers: []sharedevents.Actor{}},
		RoundDeleteAuthorizedV1: {Payload: &RoundDeleteAuthorizedPayloadV1{}, Summary: "Round Delete Authorized", Description: "Deletion authorized.", Producer: sharedevents.Actor{Service: sharedevents.ServiceBackend, Module: "round"}, Consumers: []sharedevents.Actor{}},
		RoundDeleteUnauthorizedV1: {Payload: &RoundDeleteUnauthorizedPayloadV1{}, Summary: "Round Delete Unauthorized", Description: "Deletion was not authorized.", Producer: sharedevents.Actor{Service: sharedevents.ServiceBackend, Module: "round"}, Consumers: []sharedevents.Actor{{Service: sharedevents.ServiceDiscord, Module: "round"}}},
		RoundDeletedV1:          {Payload: &RoundDeletedPayloadV1{}, Summary: "Round Deleted", Description: "Round successfully deleted.", Producer: sharedevents.Actor{Service: sharedevents.ServiceBackend, Module: "round"}, Consumers: []sharedevents.Actor{{Service: sharedevents.ServiceDiscord, Module: "round"}}},
		RoundDeleteErrorV1:      {Payload: &RoundDeleteErrorPayloadV1{}, Summary: "Round Delete Error", Description: "Round deletion failed.", Producer: sharedevents.Actor{Service: sharedevents.ServiceBackend, Module: "round"}, Consumers: []sharedevents.Actor{}},

		// Tags / tag lookup
		TagsUpdatedForScheduledRoundsV1: {Payload: &TagsUpdatedForScheduledRoundsPayloadV1{}, Summary: "Tags Updated For Scheduled Rounds", Description: "Scheduled rounds updated due to tag changes.", Producer: sharedevents.Actor{Service: sharedevents.ServiceBackend, Module: "round"}, Consumers: []sharedevents.Actor{{Service: sharedevents.ServiceDiscord, Module: "round"}}},
		RoundTagNumberRequestedV1:      {Payload: &TagLookupRequestPayloadV1{}, Summary: "Round Tag Number Requested", Description: "Request to lookup a participant tag number.", Producer: sharedevents.Actor{Service: sharedevents.ServiceBackend, Module: "round"}, Consumers: []sharedevents.Actor{{Service: sharedevents.ServiceBackend, Module: "round"}}},
	}
}
