package leaderboardevents

import sharedevents "github.com/Black-And-White-Club/frolf-bot-shared/events/shared"

// GetV1Registry returns all modern events for the leaderboard functional area
func GetV1Registry() map[string]sharedevents.EventInfo {
	return map[string]sharedevents.EventInfo{
		LeaderboardRoundFinalizedV1:   {Payload: &LeaderboardRoundFinalizedPayloadV1{}, Summary: "Leaderboard Round Finalized", Description: "Round finalized and ready for leaderboard update.", Producer: sharedevents.Actor{Service: sharedevents.ServiceBackend, Module: "round"}, Consumers: []sharedevents.Actor{{Service: sharedevents.ServiceBackend, Module: "leaderboard"}}},
		LeaderboardUpdateRequestedV1:  {Payload: &LeaderboardUpdateRequestedPayloadV1{}, Summary: "Leaderboard Update Requested", Description: "Request to update the leaderboard.", Producer: sharedevents.Actor{Service: sharedevents.ServiceBackend, Module: "leaderboard"}, Consumers: []sharedevents.Actor{{Service: sharedevents.ServiceBackend, Module: "leaderboard"}}},
		LeaderboardUpdatedV1:          {Payload: &LeaderboardUpdatedPayloadV1{}, Summary: "Leaderboard Updated", Description: "Leaderboard successfully updated.", Producer: sharedevents.Actor{Service: sharedevents.ServiceBackend, Module: "leaderboard"}, Consumers: []sharedevents.Actor{{Service: sharedevents.ServiceDiscord, Module: "leaderboard"}, {Service: sharedevents.ServiceBackend, Module: "round"}}},
		LeaderboardUpdateFailedV1:     {Payload: &LeaderboardUpdateFailedPayloadV1{}, Summary: "Leaderboard Update Failed", Description: "Leaderboard update failed.", Producer: sharedevents.Actor{Service: sharedevents.ServiceBackend, Module: "leaderboard"}, Consumers: []sharedevents.Actor{}},
		DeactivateOldLeaderboardV1:    {Payload: &DeactivateOldLeaderboardPayloadV1{}, Summary: "Deactivate Old Leaderboard", Description: "Deactivate a previous leaderboard after update.", Producer: sharedevents.Actor{Service: sharedevents.ServiceBackend, Module: "leaderboard"}, Consumers: []sharedevents.Actor{{Service: sharedevents.ServiceBackend, Module: "leaderboard"}}},

		GetLeaderboardRequestedV1: {Payload: &GetLeaderboardRequestedPayloadV1{}, Summary: "Get Leaderboard Requested", Description: "Request to retrieve leaderboard.", Producer: sharedevents.Actor{Service: sharedevents.ServiceDiscord, Module: "leaderboard"}, Consumers: []sharedevents.Actor{{Service: sharedevents.ServiceBackend, Module: "leaderboard"}}},
		GetLeaderboardResponseV1:  {Payload: &GetLeaderboardResponsePayloadV1{}, Summary: "Get Leaderboard Response", Description: "Leaderboard retrieval response.", Producer: sharedevents.Actor{Service: sharedevents.ServiceBackend, Module: "leaderboard"}, Consumers: []sharedevents.Actor{{Service: sharedevents.ServiceDiscord, Module: "leaderboard"}}},
		GetLeaderboardFailedV1:    {Payload: &GetLeaderboardFailedPayloadV1{}, Summary: "Get Leaderboard Failed", Description: "Leaderboard retrieval failed.", Producer: sharedevents.Actor{Service: sharedevents.ServiceBackend, Module: "leaderboard"}, Consumers: []sharedevents.Actor{{Service: sharedevents.ServiceDiscord, Module: "leaderboard"}}},

		LeaderboardTagAssignmentRequestedV1:      {Payload: &LeaderboardTagAssignmentRequestedPayloadV1{}, Summary: "Leaderboard Tag Assignment Requested", Description: "Request to assign a tag to a user.", Producer: sharedevents.Actor{Service: sharedevents.ServiceBackend, Module: "user"}, Consumers: []sharedevents.Actor{{Service: sharedevents.ServiceBackend, Module: "leaderboard"}}},
		LeaderboardTagAssignedV1:                 {Payload: &LeaderboardTagAssignedPayloadV1{}, Summary: "Leaderboard Tag Assigned", Description: "Tag successfully assigned to a user.", Producer: sharedevents.Actor{Service: sharedevents.ServiceBackend, Module: "leaderboard"}, Consumers: []sharedevents.Actor{{Service: sharedevents.ServiceBackend, Module: "user"}, {Service: sharedevents.ServiceDiscord, Module: "leaderboard"}}},
		LeaderboardTagAssignmentFailedV1:         {Payload: &LeaderboardTagAssignmentFailedPayloadV1{}, Summary: "Leaderboard Tag Assignment Failed", Description: "Tag assignment failed.", Producer: sharedevents.Actor{Service: sharedevents.ServiceBackend, Module: "leaderboard"}, Consumers: []sharedevents.Actor{{Service: sharedevents.ServiceBackend, Module: "user"}, {Service: sharedevents.ServiceDiscord, Module: "leaderboard"}}},
		LeaderboardBatchTagAssignmentRequestedV1: {Payload: &LeaderboardBatchTagAssignmentRequestedPayloadV1{}, Summary: "Leaderboard Batch Tag Assignment Requested", Description: "Batch tag assignment requested.", Producer: sharedevents.Actor{Service: sharedevents.ServiceBackend, Module: "score"}, Consumers: []sharedevents.Actor{{Service: sharedevents.ServiceBackend, Module: "leaderboard"}}},
		LeaderboardBatchTagAssignedV1:            {Payload: &LeaderboardBatchTagAssignedPayloadV1{}, Summary: "Leaderboard Batch Tag Assigned", Description: "Batch tag assignment completed.", Producer: sharedevents.Actor{Service: sharedevents.ServiceBackend, Module: "leaderboard"}, Consumers: []sharedevents.Actor{{Service: sharedevents.ServiceDiscord, Module: "leaderboard"}}},
		LeaderboardBatchTagAssignmentFailedV1:    {Payload: &LeaderboardBatchTagAssignmentFailedPayloadV1{}, Summary: "Leaderboard Batch Tag Assignment Failed", Description: "Batch tag assignment failed.", Producer: sharedevents.Actor{Service: sharedevents.ServiceBackend, Module: "leaderboard"}, Consumers: []sharedevents.Actor{{Service: sharedevents.ServiceDiscord, Module: "leaderboard"}}},

		LeaderboardTagUpdatedV1: {Payload: &LeaderboardTagUpdatedPayloadV1{}, Summary: "Leaderboard Tag Updated", Description: "User tag updated in the leaderboard.", Producer: sharedevents.Actor{Service: sharedevents.ServiceBackend, Module: "leaderboard"}, Consumers: []sharedevents.Actor{{Service: sharedevents.ServiceBackend, Module: "round"}, {Service: sharedevents.ServiceDiscord, Module: "leaderboard"}}},

		TagSwapRequestedV1: {Payload: &TagSwapRequestedPayloadV1{}, Summary: "Tag Swap Requested", Description: "Request to swap tags.", Producer: sharedevents.Actor{Service: sharedevents.ServiceDiscord, Module: "leaderboard"}, Consumers: []sharedevents.Actor{{Service: sharedevents.ServiceBackend, Module: "leaderboard"}}},
		TagSwapInitiatedV1: {Payload: &TagSwapInitiatedPayloadV1{}, Summary: "Tag Swap Initiated", Description: "Tag swap initiated.", Producer: sharedevents.Actor{Service: sharedevents.ServiceBackend, Module: "leaderboard"}, Consumers: []sharedevents.Actor{{Service: sharedevents.ServiceBackend, Module: "leaderboard"}}},
		TagSwapProcessedV1: {Payload: &TagSwapProcessedPayloadV1{}, Summary: "Tag Swap Processed", Description: "Tag swap processed.", Producer: sharedevents.Actor{Service: sharedevents.ServiceBackend, Module: "leaderboard"}, Consumers: []sharedevents.Actor{{Service: sharedevents.ServiceDiscord, Module: "leaderboard"}}},
		TagSwapFailedV1:    {Payload: &TagSwapFailedPayloadV1{}, Summary: "Tag Swap Failed", Description: "Tag swap failed.", Producer: sharedevents.Actor{Service: sharedevents.ServiceBackend, Module: "leaderboard"}, Consumers: []sharedevents.Actor{{Service: sharedevents.ServiceDiscord, Module: "leaderboard"}}},

		LeaderboardTraceEventV1: {Payload: &sharedevents.TracePayloadV1{}, Summary: "Leaderboard Trace Event", Description: "Tracing/observability event for leaderboard.", Producer: sharedevents.Actor{Service: sharedevents.ServiceBackend, Module: "leaderboard"}},
	}
}
