package authevents

import sharedevents "github.com/Black-And-White-Club/frolf-bot-shared/events/shared"

// GetV1Registry returns all modern events for the discord PWA functional area
// Exposes only Discord-prefixed subjects and uses shared EventInfo + Actor metadata.
func GetV1Registry() map[string]sharedevents.EventInfo {
	discordActor := sharedevents.Actor{Service: sharedevents.ServiceDiscord, Module: "pwa"}
	backendActor := sharedevents.Actor{Service: sharedevents.ServiceBackend, Module: "pwa"}

	return map[string]sharedevents.EventInfo{
		MagicLinkRequestedV1: {
			Payload:     &MagicLinkRequestedPayload{},
			Summary:     "Magic Link Requested",
			Description: "User requested a magic link for PWA dashboard access.",
			Producer:    discordActor,
			Consumers:   []sharedevents.Actor{backendActor},
		},
		MagicLinkGeneratedV1: {
			Payload:     &MagicLinkGeneratedPayload{},
			Summary:     "Magic Link Generated",
			Description: "Magic link generated by backend for PWA access.",
			Producer:    backendActor,
			Consumers:   []sharedevents.Actor{discordActor},
		},
	}
}
