// Code generated by MockGen. DO NOT EDIT.
// Source: observability/otel/tracing/tempo.go
//
// Generated by this command:
//
//	mockgen -source=observability/otel/tracing/tempo.go -destination=observability/mocks/tracer_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	message "github.com/ThreeDotsLabs/watermill/message"
	trace "go.opentelemetry.io/otel/trace"
	gomock "go.uber.org/mock/gomock"
)

// MockTracer is a mock of Tracer interface.
type MockTracer struct {
	ctrl     *gomock.Controller
	recorder *MockTracerMockRecorder
	isgomock struct{}
}

// MockTracerMockRecorder is the mock recorder for MockTracer.
type MockTracerMockRecorder struct {
	mock *MockTracer
}

// NewMockTracer creates a new mock instance.
func NewMockTracer(ctrl *gomock.Controller) *MockTracer {
	mock := &MockTracer{ctrl: ctrl}
	mock.recorder = &MockTracerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTracer) EXPECT() *MockTracerMockRecorder {
	return m.recorder
}

// InjectTraceContext mocks base method.
func (m *MockTracer) InjectTraceContext(ctx context.Context, msg *message.Message) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "InjectTraceContext", ctx, msg)
}

// InjectTraceContext indicates an expected call of InjectTraceContext.
func (mr *MockTracerMockRecorder) InjectTraceContext(ctx, msg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InjectTraceContext", reflect.TypeOf((*MockTracer)(nil).InjectTraceContext), ctx, msg)
}

// SpanContextFromContext mocks base method.
func (m *MockTracer) SpanContextFromContext(ctx context.Context) trace.SpanContext {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SpanContextFromContext", ctx)
	ret0, _ := ret[0].(trace.SpanContext)
	return ret0
}

// SpanContextFromContext indicates an expected call of SpanContextFromContext.
func (mr *MockTracerMockRecorder) SpanContextFromContext(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SpanContextFromContext", reflect.TypeOf((*MockTracer)(nil).SpanContextFromContext), ctx)
}

// StartSpan mocks base method.
func (m *MockTracer) StartSpan(ctx context.Context, name string, msg *message.Message) (context.Context, trace.Span) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartSpan", ctx, name, msg)
	ret0, _ := ret[0].(context.Context)
	ret1, _ := ret[1].(trace.Span)
	return ret0, ret1
}

// StartSpan indicates an expected call of StartSpan.
func (mr *MockTracerMockRecorder) StartSpan(ctx, name, msg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartSpan", reflect.TypeOf((*MockTracer)(nil).StartSpan), ctx, name, msg)
}

// TraceHandler mocks base method.
func (m *MockTracer) TraceHandler(h message.HandlerFunc) message.HandlerFunc {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TraceHandler", h)
	ret0, _ := ret[0].(message.HandlerFunc)
	return ret0
}

// TraceHandler indicates an expected call of TraceHandler.
func (mr *MockTracerMockRecorder) TraceHandler(h any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TraceHandler", reflect.TypeOf((*MockTracer)(nil).TraceHandler), h)
}
